services:
  - type: web
    name: christian-apologetics-rag-chatbot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: christian-apologetics
      - key: MODEL_NAME
        value: gpt-3.5-turbo
      - key: EMBEDDING_MODEL
        value: text-embedding-ada-002
      - key: MAX_TOKENS
        value: 500
      - key: TEMPERATURE
        value: 0.7
      - key: TOP_K
        value: 5
      - key: CHUNK_SIZE
        value: 1000
      - key: CHUNK_OVERLAP
        value: 200
      - key: PORT
        value: 10000

